### ISSUE TITLE
Picking random images

### ISSUE THREAD

**Issue by Nepkey** [Rekoshe/Daji#3]
First thing I thought of is stuff tagged with **anime** on pinterest. Maybe we can expand on the sites and such but for now, this is the main idea.

**Comment by Rekoshe** [comment]
![image](https://user-images.githubusercontent.com/42325581/113743789-59f7af80-9704-11eb-9478-e88cf2a9912f.png)

seems like Pinterest does not let anybody use their API...

**Comment by Nepkey** [comment]
Then how about deviant art

**Comment by Rekoshe** [comment]
I just confirmed that Deviant art makes it possible for anyone use their api and I will start working on it soon

**Comment by Rekoshe** [comment]
Done.
 Here's the final [commit](https://github.com/Rekoshe/Daji/commit/4ce9cdba414ca6f286fafc6250ec2580b874568f).
